SET PAGESIZE 100
SET LINESIZE 150
COLUMN USERNAME FORMAT A20
COLUMN DEFAULT_TABLESPACE FORMAT A20
COLUMN TEMPORARY_TABLESPACE FORMAT A20
COLUMN ACCOUNT_STATUS FORMAT A20

-- Encabezado
PROMPT LISTADO DE USUARIOS Y SUS ESQUEMAS EN LA BASE DE DATOS ORACLE:

-- Consultar los usuarios y sus detalles
SELECT 
    USERNAME, 
    DEFAULT_TABLESPACE, 
    TEMPORARY_TABLESPACE, 
    ACCOUNT_STATUS
FROM 
    DBA_USERS
ORDER BY 
    USERNAME;

-- Mostrar privilegios de los usuarios
PROMPT LISTADO DE PRIVILEGIOS ASIGNADOS A LOS USUARIOS:

SELECT 
    GRANTEE AS "USUARIO", 
    PRIVILEGE AS "PRIVILEGIO", 
    ADMIN_OPTION AS "OPCION_ADMIN"
FROM 
    DBA_SYS_PRIVS
ORDER BY 
    GRANTEE;

-- Listar los roles asignados a cada usuario
PROMPT LISTADO DE ROLES ASIGNADOS A LOS USUARIOS:

SELECT 
    GRANTEE AS "USUARIO", 
    GRANTED_ROLE AS "ROL", 
    ADMIN_OPTION AS "OPCION_ADMIN"
FROM 
    DBA_ROLE_PRIVS
ORDER BY 
    GRANTEE;
